swagger: "2.0"
info:
  version: "2024-06-25T09:42:43Z"
  title: "test_123"
  description: "API for performing operations with integer parameters"
  termsOfService: "http://example.com/terms/"
  contact:
    name: "API Support"
    url: "http://example.com/support"
    email: "support@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "izrli5s926.execute-api.eu-west-1.amazonaws.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /test:
    get:
      summary: "Retrieve test information"
      description: "This endpoint retrieves test information."
      produces:
      - "application/json"
      parameters:
      - name: "num1"
        in: "query"
        required: true
        type: "integer"
        description: "An example integer parameter, must be a positive integer"
        default: 120
      - name: "num2"
        in: "query"
        required: true
        type: "integer"
        description: "An example integer parameter, must be a positive integer"
        default: 158
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      summary: "Submit test information"
      description: "This endpoint submits test information."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "The data to submit"
        required: true
        schema:
          type: "object"
          properties:
            num1:
              type: "integer"
              description: "A sample field"
            num2:
              type: "integer"
              format: "int32"
              description: "Another sample field"
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/Empty"
        "404":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  Empty:
    type: "object"
    properties:
      result:
        type: "integer"
        format: "int32"

  Error:
    type: "string"

